// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgubfgoCrOupz9--jer_gwCsM-DescXL8',
    appId: '1:964067509359:web:308ebf0a08193c9782799a',
    messagingSenderId: '964067509359',
    projectId: 'login-signup-ba1c0',
    authDomain: 'login-signup-ba1c0.firebaseapp.com',
    storageBucket: 'login-signup-ba1c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOoTM4QKuAIWUEUHwsYtdEn7If-E__E5U',
    appId: '1:964067509359:android:518a04c06cf0c3ba82799a',
    messagingSenderId: '964067509359',
    projectId: 'login-signup-ba1c0',
    storageBucket: 'login-signup-ba1c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiut8E6WeSEFeKzUQzycKTuJQ_i9Z04XA',
    appId: '1:964067509359:ios:c1d0770aaa53b95782799a',
    messagingSenderId: '964067509359',
    projectId: 'login-signup-ba1c0',
    storageBucket: 'login-signup-ba1c0.appspot.com',
    iosClientId: '964067509359-4jsc5jpdkqvqn6knp1baipi43avqoqo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignUp',
  );
}
